"""add color to categories

Revision ID: 307cc00c3982
Revises: ffffb0edc658
Create Date: 2025-08-07 16:19:04.176829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '307cc00c3982'
down_revision: Union[str, Sequence[str], None] = 'ffffb0edc658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('color', sa.String(), nullable=False, server_default='#ffffff'))
    op.alter_column('categories', 'color', server_default=None)

# ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'color')
    # ### end Alembic commands ###
